"""updated cart model

Revision ID: ba64a75ccd1f
Revises: fd6897b08bf2
Create Date: 2026-02-01 19:47:24.814651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba64a75ccd1f'
down_revision: Union[str, Sequence[str], None] = 'fd6897b08bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('total_price', sa.Float(), nullable=True))
    op.drop_column('carts', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('carts', 'total_price')
    # ### end Alembic commands ###